### ISSUE TITLE
move some of methods inside your separated components

### ISSUE THREAD

**Issue by atherdon** [vadim9999/AntFarmReactNative#3]
1) i assume it's related to some form fields - move it to that field https://github.com/vadim9999/AntFarmReactNative/blob/master/src/screens/main/MainScreen.js#L54-L62
2)  looks like similar methods https://github.com/vadim9999/AntFarmReactNative/blob/master/src/screens/main/MainScreen.js#L76-L81
https://github.com/vadim9999/AntFarmReactNative/blob/master/src/screens/main/MainScreen.js#L91-L99

3) I cry when i see this method. split into 5 https://github.com/vadim9999/AntFarmReactNative/blob/master/src/screens/main/MainScreen.js#L100-L156

**Comment by vadim9999** [comment]
>3.I cry when i see this method. split into 5 https://github.com/vadim9999/AntFarmReactNative/blob/master/src/screens/main/MainScreen.js#L100-L156

@atherdon yes, I also want to separate this function from MainScreen.  What do you think If I will need to change state I call function from the selector that return object with properties should be changed
```
this.setState(getDataForState()) 
// getDataForState() returns 
// {
// editable:false,
//}
```
Can I use this?

**Comment by atherdon** [comment]
no, you just make it more complicated.
first of all - remove that if - if - if statement.
and it will show you a better way

**Comment by vadim9999** [comment]
@atherdon is ti bad ? https://github.com/vadim9999/AntFarmReactNative/blob/master/src/screens/main/MainScreen.js#L108
and in selector https://github.com/vadim9999/AntFarmReactNative/blob/master/src/selector/selector.js#L94 
Should I change back?

**Comment by vadim9999** [comment]
ok understood, make it that was  before

**Comment by atherdon** [comment]
still can be better. just split into few chunks

**Comment by vadim9999** [comment]
@atherdon should I add variable in props validation. When I started eslint it displays some errorr in each component
```
145:41  error    'navigation' is missing in props validation                                                 react/prop-type
```

**Comment by atherdon** [comment]
i cannot be better than ESLint
if he need it - do it
